spring:
  application:
    name: eureka_server
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8761
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
management:
  endpoints:
    web:
      exposure:
        include: '*'