spring:
  application:
    name: eureka_server
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8761
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
management:
  endpoints:
    web:
      exposure:
        include: '*'