server:
  port: 80

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: server
              uri: lb://server
              predicates:
                - Path=/server/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      path-mapping:
        health: healthcheck
      exposure:
        include: '*'