server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            server:
#              - uri: http://10.0.1.1:80
    gateway:
      server:
        webflux:
          routes:
            - id: server
              uri: lb://server
              predicates:
                - Path= server/**
          httpclient:
            pool:
              metrics: true
          default-filters:
            - StripPrefix=1
            - Metrics
            - ModifyRequest
            - ModifyResponse
            - name: Retry
              args:
                methods: GET, POST
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                backoff:
                  firstBackoff: 5ms
                  maxBackoff: 5ms
          metrics:
            enabled: true

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info