server:
  port: 8081
spring:
  application:
    name: scaling_server
eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
        defaultZone: http://10.0.10.1:8761/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
