server:
  port: 80
spring:
  application:
    name: server
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info
