FROM ubuntu/nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY keepalived.conf /etc/keepalived/keepalived.conf

RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    iproute2 \
    curl \
    telnet \
    keepalived \
    vim
    

CMD ["service keepalived start -D && nginx"]
